name: Sync Security Findings to Jira

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      # Step 4: Check file permissions
      - name: Check file permissions
        run: ls -la .github/scripts

      # Step 5: Run vulnerability sync script
      - name: Run vulnerability sync script
        run: python $GITHUB_WORKSPACE/.github/scripts/sync_vulnerabilities.py  # Absolute path using GITHUB_WORKSPACE
        env:
          GITHUB_TOKEN: ${{ github.token }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EPIC_KEY: ${{ secrets.JIRA_EPIC_KEY }}
