name: Sync Security Findings to Jira

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Print current working directory
        run: pwd

      - name: Run vulnerability sync script
        run: |
          echo "Running sync_vulnerabilities.py..."
          python .github/scripts/sync_vulnerabilities.py
        env:
          GITHUB_TOKEN: ${{ github.token }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EPIC_KEY: ${{ secrets.JIRA_EPIC_KEY }}
