name: Sync Security Vulnerabilities to Jira

on:
  security_events:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily sync

jobs:
  sync-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
          
      - name: Run Sync Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_EPIC_KEY: ${{ secrets.JIRA_EPIC_KEY }}
        run: python .github/scripts/sync_vulnerabilities.py
